package com.smartroomsearch.app.model

import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale

object ExternalRoomsData {
    private val isoFormat = SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss'Z'", Locale.getDefault())

    fun getExternalRooms(): List<Room> {
        val now = System.currentTimeMillis()
        return listOf(
            Room(
                id = 134719785,
                title = "[Chợ Tốt Nhà] NGAY ĐẠI HỌC VĂN LANG, HỌC VIỆN HÀNH CHÍNH, CÔNG NGHIỆP, MẶT TIỀN DQH",
                description = "Phòng trọ mới xây mặt tiền Dương Quảng Hàm, ngay ĐH Văn Lang CS3, IUH, Học Viện Hành Chính. Full nội thất tiện nghi, giờ giấc tự do, bảo vệ 24/7.",
                address = "Đường Dương Quảng Hàm, Phường 5, Quận Gò Vấp",
                price = 4000000.0,
                area = 25.0,
                images = listOf(
                    "https://cdn.chotot.com/ZsqIuZjmAdMcNgguJqlHjH_6qJYEE0n-cFRXcq4fVMc/preset:view/plain/ebe9fc081551549bf89db893d4e0b66a-3002333277913150393.jpg"
                ),
                status = RoomStatus.available,
                electricity = 3800,
                water = 100000,
                internet = 100000,
                serviceFee = 150000,
                maxPeople = 2,
                district = "Gò Vấp",
                city = "TP.HCM",
                lat = 10.8285,
                lng = 106.6905,
                amenities = listOf("Máy lạnh", "Gác xép", "Tủ lạnh", "Wifi tốc độ cao", "Camera an ninh", "Giờ giấc tự do"),
                phone = "0908123456",
                zaloLink = "https://zalo.me/0908123456",
                views = 512,
                contacts = 42,
                isFeatured = true,
                isNew = true,
                isCheap = false,
                rating = 4.9,
                source = "nhatot",
                externalUrl = "https://www.nhatot.com/134719785.htm",
                createdAt = isoFormat.format(Date(now - 60000)),
                updatedAt = isoFormat.format(Date(now - 60000))
            ),
            Room(
                id = 134884371,
                title = "[Chợ Tốt Nhà] Phòng Trệt Nguyễn Oanh Full Nội Thất Bếp To rộng rãi chỉ 5tr",
                description = "Phòng trệt Nguyễn Oanh diện tích 30m2, bếp riêng rộng rãi, full nội thất cao cấp: máy lạnh, tủ lạnh, giường nệm. Không chung chủ, khóa vân tay.",
                address = "Đường Nguyễn Oanh, Phường 17, Quận Gò Vấp",
                price = 5000000.0,
                area = 30.0,
                images = listOf(
                    "https://cdn.chotot.com/xUqht7M-0JxyC2N5TP9_g40-QDHGGDjI7mEC1T_2RUQ/preset:view/plain/5f174252eee4ecb1f43e17ec7806c0c9-3003641517058168618.jpg"
                ),
                status = RoomStatus.available,
                electricity = 3800,
                water = 100000,
                internet = 100000,
                serviceFee = 150000,
                maxPeople = 3,
                district = "Gò Vấp",
                city = "TP.HCM",
                lat = 10.8354,
                lng = 106.6775,
                amenities = listOf("Máy lạnh", "Tủ lạnh", "Khu bếp riêng", "Bãi xe rộng", "Giờ giấc tự do"),
                phone = "0938123456",
                zaloLink = "https://zalo.me/0938123456",
                views = 420,
                contacts = 31,
                isFeatured = true,
                isNew = true,
                isCheap = false,
                rating = 4.8,
                source = "nhatot",
                externalUrl = "https://www.nhatot.com/134884371.htm",
                createdAt = isoFormat.format(Date(now - 120000)),
                updatedAt = isoFormat.format(Date(now - 120000))
            ),
            Room(
                id = 702593,
                title = "[Phongtro123] Ký túc xá Q7 gần Lotte Mart Q7 chỉ 1tr1 trọn gói",
                description = "Ký túc xá cao cấp Q7, gần ĐH Tôn Đức Thắng, RMIT, UFM, gần Lotte Mart Q7. Giá 1.1tr trọn gói bao điện nước, máy lạnh 24/24, wifi.",
                address = "34 Đường 36, Phường Tân Hưng, Quận 7",
                price = 1100000.0,
                area = 25.0,
                images = listOf(
                    "https://pt123.cdn.static123.com/images/thumbs/450x300/fit/2026/09/03/img-6803_1788369345.png"
                ),
                status = RoomStatus.available,
                electricity = 0,
                water = 0,
                internet = 0,
                serviceFee = 0,
                maxPeople = 1,
                district = "Quận 7",
                city = "TP.HCM",
                lat = 10.7431,
                lng = 106.7002,
                amenities = listOf("Máy lạnh", "Giường nệm", "Tủ đồ riêng", "Wifi tốc độ cao", "Camera an ninh", "Máy giặt chung"),
                phone = "0931313570",
                zaloLink = "https://zalo.me/0931313570",
                views = 680,
                contacts = 78,
                isFeatured = true,
                isNew = true,
                isCheap = true,
                rating = 4.9,
                source = "phongtro123",
                externalUrl = "https://phongtro123.com/kytucxa-com-vn-chi-nhanh-q7-tron-goi-1tr1-gan-lotte-mart-pr702593.html",
                createdAt = isoFormat.format(Date(now - 180000)),
                updatedAt = isoFormat.format(Date(now - 180000))
            ),
            Room(
                id = 134947646,
                title = "[Chợ Tốt Nhà] DUPLEX CỬA SỔ TRỜI CÁCH HUIT 100m, FULL NT ĐẦY ĐỦ",
                description = "Phòng Duplex gác cao không đụng đầu, có cửa sổ trời thoáng mát, cách ĐH Công Thương (HUIT) 100m. Trang bị full nội thất mới 100%.",
                address = "Đường Tây Thạnh, Phường Tây Thạnh, Quận Tân Phú",
                price = 4300000.0,
                area = 28.0,
                images = listOf(
                    "https://cdn.chotot.com/dzKewTRu61rsot4VB3BJ5H6j70TGWdYGnWEOCfqvsao/preset:view/plain/ddd387e922543d006a057af8a728bb30-3004135045443229674.jpg"
                ),
                status = RoomStatus.available,
                electricity = 3800,
                water = 100000,
                internet = 100000,
                serviceFee = 150000,
                maxPeople = 3,
                district = "Tân Phú",
                city = "TP.HCM",
                lat = 10.8122,
                lng = 106.6288,
                amenities = listOf("Máy lạnh", "Gác xép", "Cửa sổ", "Máy giặt riêng", "Wifi tốc độ cao"),
                phone = "0918123456",
                zaloLink = "https://zalo.me/0918123456",
                views = 390,
                contacts = 29,
                isFeatured = true,
                isNew = true,
                isCheap = false,
                rating = 4.7,
                source = "nhatot",
                externalUrl = "https://www.nhatot.com/134947646.htm",
                createdAt = isoFormat.format(Date(now - 240000)),
                updatedAt = isoFormat.format(Date(now - 240000))
            ),
            Room(
                id = 649687,
                title = "[Phongtro123] GẦN NGOẠI THƯƠNG, GTVT, HUTECH, HỒNG BÀNG, UEF - UNG VĂN KHIÊM BÌNH THẠNH",
                description = "Chính chủ cho thuê phòng trọ hẻm xe hơi Ung Văn Khiêm, gần ĐH Ngoại Thương, HUTECH, GTVT. Phòng sạch sẽ, có máy lạnh, kệ bếp, WC khép kín.",
                address = "97/13 Đường Ung Văn Khiêm, Phường 25, Quận Bình Thạnh",
                price = 3500000.0,
                area = 22.0,
                images = listOf(
                    "https://pt123.cdn.static123.com/images/thumbs/450x300/fit/2024/03/29/2_1711684797.jpg"
                ),
                status = RoomStatus.available,
                electricity = 3800,
                water = 100000,
                internet = 80000,
                serviceFee = 100000,
                maxPeople = 2,
                district = "Bình Thạnh",
                city = "TP.HCM",
                lat = 10.8032,
                lng = 106.7175,
                amenities = listOf("Máy lạnh", "Khu bếp riêng", "WC riêng", "Wifi tốc độ cao", "Chỗ để xe free"),
                phone = "0909814679",
                zaloLink = "https://zalo.me/0909814679",
                views = 560,
                contacts = 52,
                isFeatured = true,
                isNew = true,
                isCheap = true,
                rating = 4.8,
                source = "phongtro123",
                externalUrl = "https://phongtro123.com/chinh-chu-cho-thue-phong-tro-duong-ung-van-khiem-quan-binh-thanh-pr649687.html",
                createdAt = isoFormat.format(Date(now - 300000)),
                updatedAt = isoFormat.format(Date(now - 300000))
            ),
            Room(
                id = 712293,
                title = "[Phongtro123] Ký túc xá Q1 cách Cao Đẳng Cao Thắng 500m trọn gói 1tr4",
                description = "KTX Quận 1 cao cấp ngay trung tâm, cách Chợ Bến Thành và Cao Đẳng Kỹ Thuật Cao Thắng 500m. Bao trọn gói điện nước sinh hoạt, wifi.",
                address = "29 Đường Calmette, Phường Bến Thành, Quận 1",
                price = 1400000.0,
                area = 20.0,
                images = listOf(
                    "https://pt123.cdn.static123.com/images/thumbs/450x300/fit/2026/09/01/img-6803_1788232468.png"
                ),
                status = RoomStatus.available,
                electricity = 0,
                water = 0,
                internet = 0,
                serviceFee = 0,
                maxPeople = 1,
                district = "Quận 1",
                city = "TP.HCM",
                lat = 10.7698,
                lng = 106.6978,
                amenities = listOf("Máy lạnh", "Giường nệm", "Tủ đồ cá nhân", "Wifi tốc độ cao", "Camera an ninh"),
                phone = "0931313570",
                zaloLink = "https://zalo.me/0931313570",
                views = 480,
                contacts = 39,
                isFeatured = false,
                isNew = true,
                isCheap = true,
                rating = 4.7,
                source = "phongtro123",
                externalUrl = "https://phongtro123.com/ky-tuc-xa-q1-cach-cao-dang-cao-thang-500m-tron-goi-1tr4-pr712293.html",
                createdAt = isoFormat.format(Date(now - 360000)),
                updatedAt = isoFormat.format(Date(now - 360000))
            ),
            Room(
                id = 39821345,
                title = "[Batdongsan] Cho thuê phòng trọ cao cấp full nội thất ngay Trung tâm Quận 11",
                description = "Phòng trọ cao cấp ngay trung tâm Quận 11 gần Parkson Flemington, ĐH Bách Khoa. Trang bị full nội thất cao cấp: máy lạnh inverter, tủ quần áo, giường nệm.",
                address = "Đường Lê Đại Hành, Phường 11, Quận 11",
                price = 3800000.0,
                area = 25.0,
                images = listOf(
                    "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=800&q=80"
                ),
                status = RoomStatus.available,
                electricity = 3800,
                water = 100000,
                internet = 100000,
                serviceFee = 150000,
                maxPeople = 2,
                district = "Quận 11",
                city = "TP.HCM",
                lat = 10.7645,
                lng = 106.6542,
                amenities = listOf("Máy lạnh", "Tủ lạnh", "WC riêng", "Bãi xe rộng", "Giờ giấc tự do"),
                phone = "0977112233",
                zaloLink = "https://zalo.me/0977112233",
                views = 720,
                contacts = 64,
                isFeatured = true,
                isNew = false,
                isCheap = false,
                rating = 4.8,
                source = "batdongsan",
                externalUrl = "https://batdongsan.com.vn/cho-thue-phong-tro-nha-tro-tp-hcm",
                createdAt = isoFormat.format(Date(now - 420000)),
                updatedAt = isoFormat.format(Date(now - 420000))
            ),
            Room(
                id = 39751289,
                title = "[Batdongsan] Căn hộ mini studio ban công thoáng mát gần Lotte Mart Quận 7",
                description = "Căn hộ studio mini diện tích 32m2 có ban công thoáng mát, view đẹp. Đầy đủ tiện nghi: máy lạnh, máy giặt riêng, bếp nấu ăn, thang máy, hầm giữ xe.",
                address = "28 Đường số 9, Phường Tân Phú, Quận 7",
                price = 4500000.0,
                area = 32.0,
                images = listOf(
                    "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=800&q=80"
                ),
                status = RoomStatus.available,
                electricity = 4000,
                water = 120000,
                internet = 100000,
                serviceFee = 200000,
                maxPeople = 2,
                district = "Quận 7",
                city = "TP.HCM",
                lat = 10.7385,
                lng = 106.7112,
                amenities = listOf("Máy lạnh", "Ban công", "Máy giặt riêng", "Thang máy", "Khu bếp riêng"),
                phone = "0912345678",
                zaloLink = "https://zalo.me/0912345678",
                views = 850,
                contacts = 71,
                isFeatured = true,
                isNew = false,
                isCheap = false,
                rating = 4.9,
                source = "batdongsan",
                externalUrl = "https://batdongsan.com.vn/cho-thue-phong-tro-nha-tro-tp-hcm",
                createdAt = isoFormat.format(Date(now - 480000)),
                updatedAt = isoFormat.format(Date(now - 480000))
            )
        )
    }
}
